<<<<<<< HEAD

=======
>>>>>>> 2fa7e6b6f80cd3c31825fefc3f96ce80eb1d1bfa
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

<<<<<<< HEAD

namespace DAL.DBEntities
{

using System;
    using System.Collections.Generic;
    
public partial class sysdiagram
{

    public string name { get; set; }

    public int principal_id { get; set; }

    public int diagram_id { get; set; }

    public Nullable<int> version { get; set; }

    public byte[] definition { get; set; }

}

=======
namespace DAL.DBEntities
{
    using System;
    using System.Collections.Generic;
    
    public partial class sysdiagram
    {
        public string name { get; set; }
        public int principal_id { get; set; }
        public int diagram_id { get; set; }
        public Nullable<int> version { get; set; }
        public byte[] definition { get; set; }
    }
>>>>>>> 2fa7e6b6f80cd3c31825fefc3f96ce80eb1d1bfa
}
